import Head from 'next/head'
import MainContent from '../components/MainContent/MainContent'

export default function Home() {
  return (
    <div>
      <Head>
        <title>React/Next.js 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContent />
    </div>
  )
}